### ISSUE TITLE
Allow progress bars to display anywhere

### ISSUE THREAD

**Issue by thansber** [MurhafSousli/ngx-progressbar#115]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### Desired functionality
We want to use multiple progress bars in our app, but we don't want to display them at the top of the page, we would like to display them within the app itself.  Is there some way to override/customize the CSS for `.ng-progress-bar` without using any deep modifiers?

We could also use a single instance of the progress bar and move it around with CSS to avoid creating multiple component instances.

**Comment by MurhafSousli** [comment]
@thansber I am not sure if I understood! Do you want multiple progress bars or a single progress bar instance?

You can override the styles from `src/styles.scss` using `.ng-progress-bar` class.

```css
.card {
   position: relative;
   overflow: hidden;
}
#bar-one, #bar-two {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
}
.ng-progress-bar {
  position: absolute;
}
```
Check this [multiple progressbar stackblitz](https://stackblitz.com/edit/ngx-progressbar-mutliple-instances?file=styles.scss)
