### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by suhaibkhan** [MurhafSousli/ngx-progressbar#123]
The progress bar is not working in IE. Is this supported in IE?  
Tested Automagic loading bar with Angular >= 5 in IE 11 and Edge, not working in both of them.

**Comment by MurhafSousli** [comment]
IE is not supported. but it is working on Edge

**Comment by mderazon** [comment]
@MurhafSousli do you know what is the issue with IE ? Maybe it's solvable.
Any idea ?

**Comment by MurhafSousli** [comment]
@mderazon it doesn't work because IE doesn't support CSS variables. 
You can use version `@ngx-progressbar/core@3.0.2` works on IE11

**Comment by relair** [comment]
I have tried @ngx-progressbar/core@3.0.2 with IE11, but it doesn't work, elements are there and they are responding (n the markup) but css doesn't seem to work correctly and progress bar and spinner are both invisible.
In the end I have used ngx-loading-bar which seems to be working fine on IE11.

**Comment by karimhernandez** [comment]
Rather than downgrading to an earlier version and leaving potential dependency incompatibilities in my project, I opted to override the specific styles which used CSS var(...) to add back support for IE11.  So far the snippet below seems to work for our app.

```scss

.ng-progress-bar {
  filter: none;
  -webkit-transition: opacity 200ms linear;
  transition: opacity  200ms linear;

  & .bar {
    background-color: red;
  }  

  &.-active .bar {
    filter: none;
    -webkit-transition: all  200ms linear;
    transition: all  200ms linear;  
  }
}

.meteor {
  -webkit-box-shadow: 0 0 10px red, 0 0 5px red;
  box-shadow: 0 0 10px red, 0 0 5px red;
}

.spinner-icon {
  border-top-color: red;
  border-left-color: red;  
}

```
