### ISSUE TITLE
Set parent container

### ISSUE THREAD

**Issue by scirneanu** [MurhafSousli/ngx-progressbar#129]
How can we set a specific parent container for the progress bar?

**Comment by MurhafSousli** [comment]
```css
.parent {
   position: relative;
}

// Set progress bar position on panel
::ng-deep {
  ng-progress {
    position: absolute !important;
    top: 0;
    left: 0;
    right: 0;
    .ng-progress-bar {
      position: absolute;
    }
  }
}
```
https://stackblitz.com/edit/ngx-progressbar-mutliple-instances
