### ISSUE TITLE
I am not able to set the thickness to the bar. Can you please give example how to set 10px thickness for the progress bar.

### ISSUE THREAD

**Issue by suhaskurade8** [MurhafSousli/ngx-progressbar#209]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

**Comment by MurhafSousli** [comment]
```scss
::ng-deep {
  .ng-bar-placeholder {
    height: 10px !important;
  }
}
```
Don't forget to set the meteor to false `<ng-progress [meteor]="false"></ng-progress>`
Check this [stackblitz](https://stackblitz.com/edit/ngx-progressbar-9wukiz?file=src/app/app.component.ts)
