### ISSUE TITLE
Set progressbar location to the top of container instead of the page

### ISSUE THREAD

**Issue by JesseZomer** [MurhafSousli/ngx-progressbar#212]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### OS and Version?

Windows 10
### Versions

latest

### Desired functionality

I would like te see a feature where you can set the progressbar to the top of your container instead of the page. At the moment I'm using https://github.com/aitboudad/ngx-loading-bar because this has a [fixed]="false" feature, where the progressbar gets set to top of the component you place it in.

**Comment by MurhafSousli** [comment]
```css
::ng-deep {
  .parent {
    position: relative;
    ng-progress {
      position: static;
      .ng-progress-bar {
         position: absolute;
      }
    }
  }
}
```
check this [stackblitz](https://stackblitz.com/edit/ngx-progressbar-mutliple-instances?file=app%2Fapp.component.scss)

dup of #73 #129

I will add an option for this
