### ISSUE TITLE
CSS positionning

### ISSUE THREAD

**Issue by NumericFactory** [MurhafSousli/ngx-progressbar#73]
Hi,
Great Job and thanks for this repo.
Please can you tell me if it's possible to positionning the bar with CSS ?

**Comment by MurhafSousli** [comment]
Hi @NumericFactory, Sure you can override the styles for `.ng-progress` class, these are the default css rules for positioning
```css
.ng-progress {
    z-index: 999999;
    top: 0;
    left: 0;
    width: 100%;
    position: fixed;
  }
```
Check the components' styles for more details
